//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationMapReduce.MRServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MRServiceReference.IMapReduceService", CallbackContract=typeof(WebApplicationMapReduce.MRServiceReference.IMapReduceServiceCallback), SessionMode=System.ServiceModel.SessionMode.Required)]
    public interface IMapReduceService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMapReduceService/MapReduce", ReplyAction="http://tempuri.org/IMapReduceService/MapReduceResponse")]
        System.Collections.Generic.List<System.Collections.Generic.KeyValuePair<string, int>> MapReduce(System.Collections.Generic.List<string> data, System.Collections.Generic.List<string> outputKeys);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMapReduceService/MapReduce", ReplyAction="http://tempuri.org/IMapReduceService/MapReduceResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<System.Collections.Generic.KeyValuePair<string, int>>> MapReduceAsync(System.Collections.Generic.List<string> data, System.Collections.Generic.List<string> outputKeys);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMapReduceServiceCallback {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMapReduceService/Map", ReplyAction="http://tempuri.org/IMapReduceService/MapResponse")]
        System.Collections.Generic.List<System.Collections.Generic.KeyValuePair<string, int>> Map(string value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMapReduceService/Reduce", ReplyAction="http://tempuri.org/IMapReduceService/ReduceResponse")]
        System.Collections.Generic.List<System.Collections.Generic.KeyValuePair<string, int>> Reduce(string keyOutput, System.Collections.Generic.List<System.Collections.Generic.List<System.Collections.Generic.KeyValuePair<string, int>>> intermediateKeyPairBlocks);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMapReduceServiceChannel : WebApplicationMapReduce.MRServiceReference.IMapReduceService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MapReduceServiceClient : System.ServiceModel.DuplexClientBase<WebApplicationMapReduce.MRServiceReference.IMapReduceService>, WebApplicationMapReduce.MRServiceReference.IMapReduceService {
        
        public MapReduceServiceClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public MapReduceServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public MapReduceServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public MapReduceServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public MapReduceServiceClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public System.Collections.Generic.List<System.Collections.Generic.KeyValuePair<string, int>> MapReduce(System.Collections.Generic.List<string> data, System.Collections.Generic.List<string> outputKeys) {
            return base.Channel.MapReduce(data, outputKeys);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<System.Collections.Generic.KeyValuePair<string, int>>> MapReduceAsync(System.Collections.Generic.List<string> data, System.Collections.Generic.List<string> outputKeys) {
            return base.Channel.MapReduceAsync(data, outputKeys);
        }
    }
}
